diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_joints: ["Left_Motor"]
    right_joints: ["Right_Motor"]
    wheel_separation: 0.27     # ระยะระหว่างล้อ
    wheel_radius: 0.05         # ปรับตาม URDF
    cmd_vel_timeout: 0.5
    publish_rate: 50
    velocity_rolling_window_size: 2
    odom_frame_id: "odom"
    base_frame_id: "Origin_link"
    enable_odom_tf: true
